### ISSUE TITLE
Bing Map, The specified credentials are invalid

### ISSUE THREAD

**Issue by Odenysyuk** [weiweicui/PowerBI-Routemap#14]
Hello I try to run custom visual via code. When I open icon Develop visual in PowerBI, I see the error "The specified credentials are invalid".

![image](https://user-images.githubusercontent.com/11458536/52631872-a9e1df80-2ec8-11e9-8677-c8227e89efcb.png)

I create key in  bing map portal:
![image](https://user-images.githubusercontent.com/11458536/52631914-c1b96380-2ec8-11e9-837f-f3770860bd73.png)

and put to BingKey.
But It still doesn't work. What I miss?

**Comment by natalicontguard** [comment]
I am having the same issue. 
@Odenysyuk  did you manage to solve it?

**Comment by Ayush-at-nsit** [comment]
Hi @Odenysyuk @natalicontguard  Did you guys find a solution to this?

**Comment by natalicontguard** [comment]
> Hi @Odenysyuk @natalicontguard Did you guys find a solution to this?

the fix is in the pull request #20 . as a comment to issue #19

**Comment by weiweicui** [comment]
It seems fixed in [this version](https://github.com/weiweicui/PowerBI-Routemap/blob/master/dist/routemap.1.4.2.pbiviz), please give a try

**Comment by cybermocca** [comment]
I have try on v1.4.2, but the problems still occured : The specified credentials are invalid. You can sign up free developer account at bingmapsportal.

Is there any newer version from v1.4.2 to solve this issue ?

**Comment by gabcodec** [comment]
@cybermocca Check out my [fork](https://github.com/gabcodec/PowerBI-Routemap) with the fix. I also commented on this [issue](https://github.com/weiweicui/PowerBI-Routemap/issues/33#issuecomment-3258420402)
